### ISSUE TITLE
I am having issues getting my fork of this repo going. 

### ISSUE THREAD

**Issue by andrewmundy** [mail-my-ballot/mail-my-ballot#30]
I was wondering if anyone had any tips for getting the project up and running. I am looking to contribute some frontend to this project but I've run into troubles.

Here's my error 
`Error: Cannot find module './secrets.nogit.json'`

So far I've 
- node v12
- installed yarn
- installed now
- `yarn install`
- installed gcloud

it looks like I still have to set up 
- `env.dev.nogit.js`
- `secrets.nogit.json`

I am not sure how to set up the above steps. Any tips would be greatly appreciated. Thanks!

**Comment by ludanin** [comment]
Hello Andrew,

The sample of these files can be found within the same folder `env`, they are `secrets.sample.json` and `env.dev.sample.js` respectively.

`env.dev.nogit.js` is a development JavaScript version of the `secrets.nogit.json`, and you can see all keys/values for the file at `secrets.sample.json`

By the way, on `GOOGLE_APPLICATION_CREDENTIALS` be sure to point to a valid .json file inside `packages/server/secrets`, otherwise the server is not going to run, and the process is going to throw due to the lack of valid env variables.

On the project's README you can see the explanation and how to behind these env variables, however if you face any other issue just let me know.

**Comment by andrewmundy** [comment]
Ah I see. Okay, so it looking for `env.dev.nogit.js` so I just duplicated `env.dev.sample.js` and renamed it `env.dev.nogit.js`
