### ISSUE TITLE
Cannot configure server, do not have sufficient permission

### ISSUE THREAD

**Issue by JhonsonTian** [mail-my-ballot/mail-my-ballot#4]
Hi @tianhuil,

I can setup and run client, but I cannot complete configuring for server because of permission problems.

- Cannot generate key for firestore
![image](https://user-images.githubusercontent.com/26655399/82855728-4b623880-9f36-11ea-9b29-e3b799d78ca2.png)

- Enable Google+ API return permission for resourcemanager.projects.get and 
serviceusage.services.get
![image](https://user-images.githubusercontent.com/26655399/82855839-9714e200-9f36-11ea-86f2-f996b2bf4140.png)

- OAuth Conset
![image](https://user-images.githubusercontent.com/26655399/82856706-eeb44d00-9f38-11ea-8fa3-40c8d6d343aa.png)

- OAuth Credential
This page cannot be loaded. Maybe above settings are needed first.

Thank You

**Comment by tianhuil** [comment]
Thanks for writing!  It looks like you haven't configured the GCloud Permissions yet.  You'll need to set up your own GCloud account (it's free to get started) and add those credentials to your own repository.  Did you ever set up the Google Oauth config:
1. https://github.com/mail-my-ballot/mail-my-ballot/#dev-firestore-access
1. https://github.com/mail-my-ballot/mail-my-ballot/#google-oauth-development-of-organizer-facing-pages-only

Sorry, this isn't more clear!  Finally, feel free to push up a PR to the README.md so that others have an easier time.  Thanks for flagging this issue!

**Comment by JhonsonTian** [comment]
@tianhuil yeah, I have little experience on the server-side. I am able to run the server with no errors now, but not sure if it is working. will move on later. thanks

**Comment by michael-vote-at-home** [comment]
No worries.  If you get get your dev server sending you an email, then it should be working.

**Comment by tianhuil** [comment]
I'm closing this for now.  If there are any other questions, feel free to create a new issue.
